title: "#BornPerfect"
description: Stories from across the continent about FGM. Supported by Code for Africa and ICFJ.

url: https://bornperfect.africa
enforce_ssl: bornperfect.africa

tw_url: https://twitter.com/Code4Africa
fb_url: https://facebook.com/CodeForAfrica

google_analytics: UA-XXXXXXXX
